### ISSUE TITLE
heist/3.11.2 updates

### ISSUE THREAD

**Issue by erosson** [mapwatch/mapwatch#115]
waiting on https://github.com/OmegaK2/PyPoE, I think. discussion happening in https://www.reddit.com/r/pathofexiledev/ and various discord channels linked there

`pypoe_ui` shows most interesting data is now in `.bundle.bin`s

this blocks getting correct map regions, i18n, and new hideouts

```
$ yarn export:main
yarn run v1.19.1
$ bash -c "mkdir -p dist && pypoe_exporter config set ggpk_path \"`cat ggpk_paths/en`\" && pypoe_exporter dat json dist/all.json --files `node src/mainFilenames.js` && date > dist/date"
13:37:51 Config setting "ggpk_path" has been set to:

13:37:52 Reading "C:\Program Files (x86)\Grinding Gear Games\Path of Exile\content.ggpk"...
13:37:52 d:\code\mapwatch\packages\datamine\pypoe\PyPoE\poe\file\ggpk.py:1037:
UserWarning: Invalid tag b'\x06\x00\x00\x00' - seeking next valid tag
13:37:53 Reading .dat files
13:37:53 Traceback (most recent call last):
  File "d:\code\mapwatch\packages\datamine\pypoe\PyPoE\cli\core.py", line 145, in run
    code = args.func(args)
  File "d:\code\mapwatch\packages\datamine\pypoe\PyPoE\cli\exporter\dat\parsers\json.py", line 109, in handle
    dat_files = self._read_dat_files(args)
  File "d:\code\mapwatch\packages\datamine\pypoe\PyPoE\cli\exporter\dat\handler.py", line 117, in _read_dat_files
    ggpk_data = ggpk['Data']
  File "d:\code\mapwatch\packages\datamine\pypoe\PyPoE\poe\file\ggpk.py", line 819, in __getitem__
    return self.directory[item]
  File "d:\code\mapwatch\packages\datamine\pypoe\PyPoE\poe\file\ggpk.py", line 579, in __getitem__
    raise FileNotFoundError('%s/%s not found' % (
FileNotFoundError: /Data not found
```

https://github.com/poe-tool-dev/ggpk.discussion/wiki/Bundle-scheme

https://www.reddit.com/r/pathofexiledev/comments/isubgf/state_of_pathofexiledev_adapting_to_the_new_poe/g5ax8r2/

**Comment by erosson** [comment]
bundle extractor tools: https://github.com/poe-tool-dev/ggpk.discussion/wiki/Implementations

of those tools, pypoe depends on `ooz` from that link after its latest update: https://github.com/zao/ooz

```Extracting index record...
'ooz' is not recognized as an internal or external command,
operable program or batch file.
```

the author conveniently linked a precompiled exe in the poe tooldev discord, and I can't be arsed to build it myself:

> https://zao.se/~zao/poe/ooz-g53c4c6d.zip
> https://discordapp.com/channels/174993814845521922/175290321695932416/757422483853934622

it's slower now, but it works!
